version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres
  server:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
